spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_aep
    username: root
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true

  server:
    port: 8080
